### ISSUE TITLE
Issue related to "~ admin controller/updateMapping" section

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle-api-documentation#45]
link of `mapping capabilities of ElasticSearch.`  should be https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping.html

**Comment by ballinette** [comment]
should be https://www.elastic.co/guide/en/elasticsearch/reference/2.3/mapping.html  instead, as we are using ES 2.3 for now ;)
