### ISSUE TITLE
Issue related to "~ collection controller/exists" section

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-api-documentation#73]
The controller in the example should be "collection", not "exists" : 
{
  "status": 200,                      // Assuming everything went well
  "error": null,                      // Assuming everything went well
  "index": "<data index>",
  "collection": "<data collection>",
  "controller": "exists",
  "action": "exists",
  "requestId": "<unique request identifier>",
  "result": true
}

Answer from Kuzzle : 
{
  "requestId": "f0d00d9a-2a29-4cc2-a960-0ae3a680b3b3",
  "error": null,
  "controller": "collection",
  "action": "exists",
  "collection": "myCollection",
  "index": "myIndex",
  "metadata": null,
  "result": true
}

**Comment by dbengsch** [comment]
Done in kuzzleio/documentation#31
